import express, { Router } from "express";
import { createMaterialForModule, deleteMaterialForUser, getMaterialForUser, getModuleForUser, listMaterialsForModule, setMaterialExtraction } from "../db/queries";
import { MaterialError, normalizeExtractedText, validateMaterialUpload } from "../lib/materials";
import { requireUser } from "../middleware/requireUser";
import { readPrivateMaterial, removePrivateMaterial, storePrivateMaterial } from "../storage/localMaterialStorage";

export const materialsRouter = Router();
materialsRouter.use(requireUser);

materialsRouter.get("/modules/:moduleId/materials", async (request, response, next) => { try { const module = await getModuleForUser(Number(request.params.moduleId), request.user!.id); if (!module) return response.status(404).json({ error: "Module not found." }); response.json({ materials: await listMaterialsForModule(module.id) }); } catch (error) { next(error); } });
materialsRouter.post("/modules/:moduleId/materials/upload", express.raw({ type: "*/*", limit: "2mb" }), async (request, response, next) => { try { const module = await getModuleForUser(Number(request.params.moduleId), request.user!.id); if (!module) return response.status(404).json({ error: "Module not found." }); if (!Buffer.isBuffer(request.body)) return response.status(400).json({ error: "The file could not be read." }); const file = validateMaterialUpload({ filename: request.header("x-material-filename") ?? undefined, mimeType: request.header("content-type") ?? undefined, byteSize: request.body.length }); const storageKey = await storePrivateMaterial(request.body, file.extension); const material = await createMaterialForModule({ moduleId: module.id, originalFilename: file.filename, mimeType: file.mimeType, byteSize: request.body.length, storageKey }); response.status(201).json({ material }); } catch (error) { next(error); } });
materialsRouter.post("/materials/:materialId/extract", async (request, response, next) => { try { const material = await getMaterialForUser(Number(request.params.materialId), request.user!.id); if (!material) return response.status(404).json({ error: "Material not found." }); try { const extractedText = normalizeExtractedText(await readPrivateMaterial(material.storageKey)); await setMaterialExtraction(material.id, "ready", extractedText); response.json({ extractedCharacterCount: extractedText.length, status: "ready" }); } catch (error) { const message = error instanceof Error ? error.message : "Text extraction failed."; await setMaterialExtraction(material.id, "failed", undefined, message); response.status(400).json({ error: message }); } } catch (error) { next(error); } });
materialsRouter.get("/materials/:materialId/text", async (request, response, next) => { try { const material = await getMaterialForUser(Number(request.params.materialId), request.user!.id); if (!material) return response.status(404).json({ error: "Material not found." }); if (material.extractionStatus !== "ready" || !material.extractedText) return response.status(409).json({ error: "Extract text before previewing this material." }); response.json({ filename: material.originalFilename, extractedText: material.extractedText }); } catch (error) { next(error); } });
materialsRouter.delete("/materials/:materialId", async (request, response, next) => { try { const material = await deleteMaterialForUser(Number(request.params.materialId), request.user!.id); if (!material) return response.status(404).json({ error: "Material not found." }); await removePrivateMaterial(material.storageKey); response.status(204).end(); } catch (error) { next(error); } });
