import { Download, Upload } from "lucide-react";
import { ChangeEvent, useRef, useState } from "react";
import { exportModuleBackup, restoreModuleBackup, type StudyModule } from "../lib/api";

export function ModuleBackupPanel({ module, onRestored }: { module: StudyModule; onRestored: () => Promise<void> }) {
  const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const download = async () => { try { setBusy(true); const backup = await exportModuleBackup(module.id); const blob = new Blob([JSON.stringify(backup, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${module.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "recall-module"}-backup.json`; link.click(); URL.revokeObjectURL(url); setMessage("Backup downloaded. It contains the module guide, flashcards, and quizzes—not files, chat, or review history."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not create the backup."); } finally { setBusy(false); } };
  const restore = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { setBusy(true); const parsed = JSON.parse(await file.text()) as unknown; await restoreModuleBackup(parsed); await onRestored(); setMessage("Module restored as a new private module."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "That backup file is not valid."); } finally { setBusy(false); event.target.value = ""; } };
  return <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold">Portable backup</p><p className="mt-1 text-sm leading-6 text-slate-600">Export this module’s guide, flashcards, and questions as a JSON file. Restoring always creates a new module.</p><div className="mt-4 flex flex-wrap gap-3"><button type="button" className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold disabled:opacity-50" disabled={busy} onClick={() => void download()}><Download className="size-4" />Export module</button><button type="button" className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold disabled:opacity-50" disabled={busy} onClick={() => inputRef.current?.click()}><Upload className="size-4" />Restore backup</button><input ref={inputRef} className="sr-only" type="file" accept="application/json,.json" onChange={(event) => void restore(event)} /></div>{message && <p className="mt-3 text-sm text-slate-600" role="status">{message}</p>}</section>;
}
